angular.module('learnApp',
        [
            'ngRoute',
            'kdheader',
            'kdhome',
            'kdcourse',
            'birthdayParty',
            'schoolProgram',
            'kdlogin',
            'kdsignup',
            'aboutUs',
            'kdfooter'
        ]);